# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: "OnPremAgentsPool"
  runPipeline: true

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(75a700f9-db14-47c2-b97c-4481c0611f0b)'
    subscriptionId: '75a700f9-db14-47c2-b97c-4481c0611f0b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Candidates_Homework_Lana'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'storage02.json'
    overrideParameters: '-storageName "lanastorageaccount1"'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(75a700f9-db14-47c2-b97c-4481c0611f0b)'
    subscriptionId: '75a700f9-db14-47c2-b97c-4481c0611f0b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Candidates_Homework_Lana'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'storage02.json'
    overrideParameters: '-storageName "lanastorageaccount2"'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(75a700f9-db14-47c2-b97c-4481c0611f0b)'
    subscriptionId: '75a700f9-db14-47c2-b97c-4481c0611f0b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Candidates_Homework_Lana'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'windows_server.json'
    overrideParameters: '-adminUsername "lanajahshan" -adminPassword $(adminPassword)'
    deploymentMode: 'Incremental'